server:
  port: 5008
access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}
fe-client:
  url: ${FE_CLIENT_URL}
spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://${MONGO_URI}
      database: ${MONGO_DATABASE}
  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org.springframework.security: ${LOGGING_LEVEL}